export * as plugin from "./core/plugin.js";
export const tau: number;
export const pi: number;
export const e: number;
export { renderText } from "./core/drawable.js";
export * as kit from "./kit.js";
export namespace adapt {
    export namespace asymmetric {
        export { SymPyAdapter };
        export { SageAdapter };
        export { createSymbolicAdapter };
        export { defaultAdapter };
    }
    export { irToAsymptote as asymptote };
    export { tikzToSVG as tikzjax };
    export namespace jsxgraph {
        export { irToJSXGraph };
        export { buildJSXGraphHTML };
    }
    export namespace katex {
        export { katexRender };
        export { katexify };
    }
}
export const ray: ((...a: any[]) => any) & {
    [k: string]: (...a: any[]) => any;
};
export function arc(): void;
export function sector(): void;
export function torus(): void;
export function cube(): void;
export function prism(): void;
export function pyramid(): void;
declare namespace _default {
    export { scene };
    export { point };
    export { vector };
    export { line };
    export { segment };
    export { curve };
    export { circle };
    export { ellipse };
    export { parabola };
    export { hyperbola };
    export { polygon };
    export { triangle };
    export { quad };
    export { regular };
    export { square };
    export { rectangle };
    export { region };
    export { vectorField };
    export { sphere };
    export { plane };
    export { cylinder };
    export { cone };
    export { surface };
    export { polyhedron };
    export { curve3 };
    export { arrow3 };
    export { surfaceParam };
    export { axes3 };
    export { quadrics };
    export { circle3 };
    export { frame3 };
    export { transform };
    export { annotate };
    export { tex };
    export { tau };
    export { pi };
    export { e };
    export { use };
    export { plugins };
    export { xy };
    export { range };
    export { view };
}
export default _default;
import { use } from './core/plugin.js';
import { plugins } from './core/plugin.js';
import { PluginError } from './core/plugin.js';
import { Scene } from './core/scene.js';
export function scene(): Scene;
export namespace scene {
    function cartesian(): Scene;
}
import { panels } from './backend/scene-ir.js';
import { node } from './core/node.js';
import { point } from './shapes/point.js';
import { toPoint } from './shapes/point.js';
import { vector } from './shapes/vector.js';
import { line } from './shapes/line.js';
import { segment } from './shapes/segment.js';
import { curve } from './shapes/curve.js';
import { circle } from './shapes/circle.js';
import { ellipse } from './shapes/ellipse.js';
import { parabola } from './shapes/parabola.js';
import { hyperbola } from './shapes/hyperbola.js';
import { polygon } from './shapes/polygon.js';
import { triangle } from './shapes/polygon.js';
import { quad } from './shapes/polygon.js';
import { regular } from './shapes/polygon.js';
import { square } from './shapes/polygon.js';
import { rectangle } from './shapes/rectangle.js';
import { region } from './shapes/region.js';
import { vectorField } from './shapes/vectorfield.js';
import { vectorField3 } from './shapes/threeD2.js';
import { sphere } from './shapes/threeD.js';
import { plane } from './shapes/threeD.js';
import { cylinder } from './shapes/threeD2.js';
import { cone } from './shapes/threeD2.js';
import { surface } from './shapes/threeD2.js';
import { polyhedron } from './shapes/threeD2.js';
import { curve3 } from './shapes/threeD3.js';
import { arrow3 } from './shapes/threeD3.js';
import { surfaceParam } from './shapes/threeD3.js';
import { axes3 } from './shapes/threeD3.js';
import { quadrics } from './shapes/threeD3.js';
import { circle3 } from './shapes/threeD3.js';
import { frame3 } from './shapes/threeD3.js';
import { cmapColor } from './shapes/threeD3.js';
import { shade } from './shapes/threeD3.js';
import { mat } from './linalg.js';
import { vec } from './linalg.js';
import { Matrix } from './linalg.js';
import { cplx } from './complex.js';
import { Complex } from './complex.js';
import transform from './transform.js';
import annotate from './annotate.js';
import { tex } from './symbolic/tex.js';
import { Sym } from './symbolic/sym.js';
import { TYPE as typography } from './backend/fonts.js';
import { xy } from './core/template.js';
import { range } from './core/template.js';
import { view } from './core/template.js';
import { Point } from './shapes/point.js';
import { Vector } from './shapes/vector.js';
import { Line } from './shapes/line.js';
import { Segment } from './shapes/segment.js';
import { Curve } from './shapes/curve.js';
import { Circle } from './shapes/circle.js';
import { Ellipse } from './shapes/ellipse.js';
import { Parabola } from './shapes/parabola.js';
import { Hyperbola } from './shapes/hyperbola.js';
import { Polygon } from './shapes/polygon.js';
import { Rectangle } from './shapes/rectangle.js';
import { Region } from './shapes/region.js';
import { VectorField } from './shapes/vectorfield.js';
import { Sphere } from './shapes/threeD.js';
import { Plane } from './shapes/threeD.js';
import { Cylinder } from './shapes/threeD2.js';
import { Cone } from './shapes/threeD2.js';
import { Surface } from './shapes/threeD2.js';
import { Polyhedron } from './shapes/threeD2.js';
import { Curve3 } from './shapes/threeD3.js';
import { Drawable } from './core/drawable.js';
import { SymPyAdapter } from './symbolic/adapter.js';
import { SageAdapter } from './symbolic/adapter.js';
import { createSymbolicAdapter } from './symbolic/adapter.js';
import { defaultAdapter } from './symbolic/adapter.js';
import irToAsymptote from './backend/asymptote.js';
import { tikzToSVG } from './backend/tikzjax.js';
import { irToJSXGraph } from './backend/jsxgraph.js';
import { buildJSXGraphHTML } from './backend/jsxgraph.js';
import { katexRender } from './backend/katex.js';
import { katexify } from './backend/katex.js';
export { use, plugins, PluginError, Scene, panels, node, point, toPoint, vector, line, segment, curve, circle, ellipse, parabola, hyperbola, polygon, triangle, quad, regular, square, rectangle, region, vectorField, vectorField3, sphere, plane, cylinder, cone, surface, polyhedron, curve3, arrow3, surfaceParam, axes3, quadrics, circle3, frame3, cmapColor, shade, mat, vec, Matrix, cplx, Complex, transform, annotate, tex, Sym, typography, xy, range, view, Point, Vector, Line, Segment, Curve, Circle, Ellipse, Parabola, Hyperbola, Polygon, Rectangle, Region, VectorField, Sphere, Plane, Cylinder, Cone, Surface, Polyhedron, Curve3, Drawable };
